services:
  proxy:
    image: traefik:v3.0
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-lets:/letsencrypt
    restart: unless-stopped

  public-gateway:
    labels:
      - traefik.enable=true
      - traefik.http.routers.gateway.rule=Host(`${GATEWAY_HOST}`)
      - traefik.http.routers.gateway.entrypoints=websecure
      - traefik.http.routers.gateway.tls=true
      - traefik.http.routers.gateway.tls.certresolver=le
      - traefik.http.services.gateway.loadbalancer.server.port=4430

volumes:
  traefik-lets:
